columns:
  - URL_LENGTH: int64
  - SHORTENING_SERVICE: int64
  - HAVING_AT_SYMBOL: int64
  - DOUBLE_SLASH_REDIRECTING: int64
  - PREFIX_SUFFIX: int64
  - HAVING_SUB_DOMAIN: int64
  - SSL_FINAL_STATE: int64
  - DOMAIN_REGISTRATION_LENGTH: int64
  - FAVICON: int64
  - PORT: int64
  - HTTPS_TOKEN: int64
  - REQUEST_URL: int64
  - URL_OF_ANCHOR: int64
  - LINKS_IN_TAGS: int64
  - SFH: int64
  - SUBMITTING_TO_EMAIL: int64
  - ABNORMAL_URL: int64
  - REDIRECT: int64
  - ON_MOUSEOVER: int64
  - RIGHT_CLICK: int64
  - POPUP_WINDOW: int64
  - IFRAME: int64
  - AGE_OF_DOMAIN: int64
  - DNS_RECORD: int64
  - WEB_TRAFFIC: int64
  - PAGE_RANK: int64
  - GOOGLE_INDEX: int64
  - LINKS_POINTING_TO_PAGE: int64
  - STATISTICAL_REPORT: int64
  - RESULT: int64
numerical_columns:
  - HAVING_IP_ADDRESS
  - URL_LENGTH
  - SHORTENING_SERVICE
  - HAVING_AT_SYMBOL
  - DOUBLE_SLASH_REDIRECTING
  - PREFIX_SUFFIX
  - HAVING_SUB_DOMAIN
  - SSL_FINAL_STATE
  - DOMAIN_REGISTRATION_LENGTH
  - FAVICON
  - PORT
  - HTTPS_TOKEN
  - REQUEST_URL
  - URL_OF_ANCHOR
  - LINKS_IN_TAGS
  - SFH
  - SUBMITTING_TO_EMAIL
  - ABNORMAL_URL
  - REDIRECT
  - ON_MOUSEOVER
  - RIGHT_CLICK
  - POPUP_WINDOW
